source/accounts/urls.py
from django.urls import path, include
from accounts import views as account_views


app_name = "accounts"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("create/", account_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", account_views.UserDetailView.as_view(), name="profile"),
    path('<int:pk>/change/', account_views.UserChangeView.as_view(), name='change'),
    path("<int:pk>/change-password/", account_views.UserPasswordChangeView.as_view(), name="change_password"),
    path("<int:pk>/coefficient/", account_views.CoefficientAddView.as_view(), name="coefficient")
]

source/sliding_systems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("webapp.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views


app_name = "webapp"

urlpatterns = [
    path('', webapp_views.IndexView.as_view(), name="index"),
    path('gallary/new/', webapp_views.GallaryCreateView.as_view(), name="gallary_create"),
    path('gallary/<int:pk>/delete/', webapp_views.GallaryDeleteView.as_view(), name="gallary_delete"),
    path('products/', webapp_views.ProductView.as_view(), name='product'),
    path('section_add/', webapp_views.SectionAddView.as_view(), name='section_add'),
    path('section/<int:pk>/delete/', webapp_views.SectionDeleteView.as_view(), name='section_del'),
    path('tire_add/', webapp_views.TireAddView.as_view(), name='tire_add'),
    path('tire/<int:pk>/delete/', webapp_views.TireDeleteView.as_view(), name='tire_del'),
    path('glass_add/', webapp_views.GlassAddView.as_view(), name='glass_add'),
    path('glass/<int:pk>/delete/', webapp_views.GlassDeleteView.as_view(), name='glass_del'),
    path('door_knob_add/', webapp_views.DoorKnobAddView.as_view(), name='door_knob_add'),
    path('door_knob/<int:pk>/delete/', webapp_views.DoorKnobDeleteView.as_view(), name='door_knob_del'),
    path('color_add/', webapp_views.ColorAddView.as_view(), name='color_add'),
    path('color/<int:pk>/delete/', webapp_views.ColorDeleteView.as_view(), name='color_del'),
    path('option_add/', webapp_views.OptionAddView.as_view(), name='option_add'),
    path('option/<int:pk>/delete/', webapp_views.OptionDeleteView.as_view(), name='option_del'),
    path('person_add/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('organization_add/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customers/', webapp_views.CustomerListView.as_view(), name='customer_list'),
    path('customer/new/person/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('customer/new/organization/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customer/<int:pk>/', webapp_views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/<int:pk>/delete/', webapp_views.CustomerDeleteView.as_view(), name='customer_del'),
    path('customer/<int:pk>/person_edit/', webapp_views.PersonEditView.as_view(), name='person_edit'),
    path('customer/<int:pk>/organization_edit/', webapp_views.OrganizationEditView.as_view(), name='organization_edit'),
    path('orders/', webapp_views.OrderView.as_view(), name='order'),
    path('order_add/', webapp_views.OrderAddView.as_view(), name='order_add'),
    path('orders/<int:pk>/delete/', webapp_views.OrderDeleteView.as_view(), name='order_del'),
    path('order/<int:pk>/', webapp_views.OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/application/', webapp_views.ApplicationFormView.as_view(), name='application_form'),
    path('order/<int:pk>/application/sliding_system_choice/', webapp_views.ApplicationSlidingSystemChoiceView.as_view(),
         name='application_sliding_system_choice'),
    path('order/<int:pk>/technical_task/', webapp_views.OrderTechnicalTaskView.as_view(), name='technical_task'),
    path('order/<int:pk>/accessories/', webapp_views.OrderAccessoriesView.as_view(), name='accessories'),
    path('order/<int:pk>/status_change/', webapp_views.OrderStatusChangeView.as_view(), name='order_status_change'),
    path('application/<int:pk>/', webapp_views.ApplicationDetailView.as_view(), name='application_detail'),
    path('application/<int:pk>/delete/', webapp_views.ApplicationDeleteView.as_view(), name='application_del'),
    path('application/<int:pk>/edit/', webapp_views.ApplicationEditView.as_view(), name='application_edit'),
    path('mechanism/create/', webapp_views.DetailsCreateView.as_view(), name='mechanism_add'),
    path('mechanism/<int:pk>/delete/', webapp_views.DetailsDeleteView.as_view(), name='mechanism_del'),
    path('mechanismkit/create/', webapp_views.MechanismKitFormView.as_view(), name='mechanismkit_form'),
    path('mechanismkit/<int:pk>/detail_del', webapp_views.MechanismKitFormDetailDeleteView.as_view(),
         name='mechanismkit_detail_del'),
    path('mechanismkit/<int:pk>/detail_add', webapp_views.MechanismKitFormDetailAddView.as_view(),
         name='mechanismkit_detail_add'),
    path('mechanismkit/<int:pk>/delete/', webapp_views.MechanismKitDeleteView.as_view(), name='mechanismkit_del'),
    path('constructor/', webapp_views.ConstructorView.as_view(), name='constructor'),
    path('slidingsystem/create', webapp_views.SlidingSystemFormView.as_view(), name='slidingsystem_add'),
    path('slidingsystem/<int:pk>/delete', webapp_views.SlidingSystemDeleteView.as_view(),
         name='slidingsystem_del'),
    path('slidingsystem/<int:pk>/section_delete', webapp_views.SlidingSystemFormSectionDeleteView.as_view(),
         name='slidingsystem_section_del'),
    path('order/<int:pk>/contract/', webapp_views.OrderContractView.as_view(), name = 'contract'),
    path('order/<int:pk>/commercial_proposal/', webapp_views.OrderCommercialProposalView.as_view(),
         name = 'commercial_proposal'),
]

source/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    phone_number = models.CharField(max_length=150, verbose_name="Контактный телефон")


source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class RegistrationForm(UserCreationForm):
    phone_number = forms.CharField(max_length=150, label="Контактный телефон")
    class Meta(UserCreationForm.Meta):
        fields = ["username", "phone_number", "password1", "password2", "groups"]
        labels = {'username': 'Логин', 'phone_number': 'Контактный телефон', 'password1': 'Пароль', 'password2': 'Повторите пароль'}

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "last_name"]
        labels = {'username': 'Логин', 'first_name': 'Имя', 'last_name': 'Фамилия'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

source/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, CreateView, UpdateView

from accounts.admin import User
from accounts.forms import RegistrationForm, ProfileChangeForm, UserChangeForm
from accounts.models import Profile
from webapp.models import Coefficient


class UserDetailView(UserPassesTestMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object() or self.request.user.is_superuser

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        users = User.objects.all()
        coefficient = get_object_or_404(Coefficient, pk=1)
        context["users"] = users
        context["coefficient"] = coefficient
        return context

class RegisterView(UserPassesTestMixin, CreateView):
    model = get_user_model()
    template_name = "registration/register.html"
    form_class = RegistrationForm

    def form_valid(self, form):
        user = form.save()
        form.save_m2m()
        Profile.objects.create(user=user)
        return redirect("accounts:profile", pk=self.request.user.pk)

    def test_func(self):
        return self.request.user.is_superuser


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object() or self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def test_func(self):
        return self.request.user.pk == self.kwargs["pk"] or self.request.user.is_superuser

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})


class CoefficientAddView(View):
    def post(self, request, *args, **kwargs):
        percent = request.POST.get('percent')
        coefficient = get_object_or_404(Coefficient, pk=1)
        coefficient.percent = percent
        coefficient.save()
        users = User.objects.all()
        return render(request, "user_detail.html", {"users": users, "user_obj": self.request.user,
                                                    "coefficient": coefficient})

source/accounts/templates/user_change.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}
     Редактировать профиль
{% endblock %}

{% block stylesheets %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "assets/plugins/fontawesome-free/css/all.min.css" %}">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static "assets/plugins/daterangepicker/daterangepicker.css" %}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{% static "assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="{% static "assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" %}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static "assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{% static "assets/plugins/select2/css/select2.min.css" %}">
  <link rel="stylesheet" href="{%static "assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{%static "assets/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css" %}">
  <!-- BS Stepper -->
  <link rel="stylesheet" href="{% static "assets/plugins/bs-stepper/css/bs-stepper.min.css" %}">
  <!-- dropzonejs -->
  <link rel="stylesheet" href="{% static "assets/plugins/dropzone/min/dropzone.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "assets/dist/css/adminlte.min.css" %}">
{% endblock stylesheets %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
    <div class="col-md-12">
        <div class="card card-danger">
            <div class="wrapper">
              <!-- Content Wrapper. Contains page content -->
              <div class="content-wrapper">
                <!-- Main content -->
                <section class="content">
                  <div class="container-fluid">
                    <!-- /.row -->
                    <div class="row">
                      <div class="col-md-12">
                        <div class="card card-default">
                          <div class="card-header d-flex justify-content-between align-items-center">
                              <h3 class="card-title">Редактировать профиль</h3>
                              <a href="{% url "accounts:profile" user_obj.pk %}" class="link-dark">Вернуться назад</a>
                          </div>
                          <div class="card-body">
                                {% if user.is_authenticated %}
                                <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    {{ profile_form|crispy }}
                                    <button class="btn btn-dark">Редактировать</button>
                                </form>
                            {% endif %}
                          </div>
                        </div>
                        <!-- /.card -->
                      </div>
                    </div>
                    <!-- /.row -->
                  </div>
                  <!-- /.container-fluid -->
                </section>
                <!-- /.content -->
              </div>
            </div>
        </div>
    </div>
</div>
<!-- /.card -->
{% endif %}
{% endblock %}

{% block javascripts %}
<!-- jQuery -->
<script src="{% static "assets/plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "assets/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- Select2 -->
<script src="{% static "assets/plugins/select2/js/select2.full.min.js" %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static "assets/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js" %}"></script>
<!-- InputMask -->
<script src="{% static "assets/plugins/moment/moment.min.js" %}"></script>
<script src="{% static "assets/plugins/inputmask/jquery.inputmask.min.js" %}"></script>
<!-- date-range-picker -->
<script src="{% static "assets/plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- bootstrap color picker -->
<script src="{% static "assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Bootstrap Switch -->
<script src="{% static "assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js" %}"></script>
<!-- BS-Stepper -->
<script src="{% static "assets/plugins/bs-stepper/js/bs-stepper.min.js" %}"></script>
<!-- dropzonejs -->
<script src="{% static "assets/plugins/dropzone/min/dropzone.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "assets/dist/js/adminlte.min.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "assets/dist/js/demo.js" %}"></script>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}
     Личный кабинет
{% endblock %}

{% block stylesheets %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "assets/plugins/fontawesome-free/css/all.min.css" %}">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static "assets/plugins/daterangepicker/daterangepicker.css" %}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{% static "assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="{% static "assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" %}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static "assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{% static "assets/plugins/select2/css/select2.min.css" %}">
  <link rel="stylesheet" href="{%static "assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{%static "assets/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css" %}">
  <!-- BS Stepper -->
  <link rel="stylesheet" href="{% static "assets/plugins/bs-stepper/css/bs-stepper.min.css" %}">
  <!-- dropzonejs -->
  <link rel="stylesheet" href="{% static "assets/plugins/dropzone/min/dropzone.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "assets/dist/css/adminlte.min.css" %}">
{% endblock stylesheets %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
    <div class="col-md-12">
        <div class="card card-danger">
            <div class="wrapper">
              <!-- Content Wrapper. Contains page content -->
              <div class="content-wrapper">
                <!-- Main content -->
                <section class="content">
                  <div class="container-fluid">
                    <!-- /.row -->
                    <div class="row">
                      <div class="col-md-12">
                        <div class="card card-default">
                          <div class="card-header d-flex justify-content-between align-items-center">
                              <h3 class="card-title">Профиль</h3>
                              <a href="{% url "webapp:index" %}" class="link-dark">Вернуться назад</a>
                          </div>
                          <div class="card-body">
                            <div style="display: inline-block; position: absolute;" class="user_avatar">
                                {% if user_obj.profile.avatar %}
                                    <img style="border-radius: 20px;" src="{{ user_obj.profile.avatar.url }}" width="150" height="150" alt="user picture">
                                {% else %}
                                    <img style="border-radius: 20px;" src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-vector-260nw-1725655669.jpg"
                                           width="150" height="150" alt="">
                                {% endif %}
                            </div>
                            <div style="display: inline-block; margin-left: 200px; position: absolute;">
                                Логин: <b>{{ user_obj.username }}</b><br>
                                Имя: <b>{{ user_obj.first_name }}</b><br>
                                Фамилия: <b>{{ user_obj.last_name }}</b><br>
                                Дата рождения: <b>
                                                {{ user_obj.profile.birth_date.day }}.{{ user_obj.profile.birth_date.month }}.{{ user_obj.profile.birth_date.year }}
                                                </b><br>
                                Контакный номер: <b>{{ user_obj.profile.phone_number }}</b><br>
                                Email: <b>{{ user_obj.email }}</b><br>
                                Должность: <b>{% for group in user_obj.groups.all %}
                                                {{ group }}
                                              {% endfor %}
                                            </b><br>
                            </div>
                            <div style="display: inline-block; margin-left: 600px;">
                                    <a class="btn btn-outline-success" style="width:350px" href="{% url 'accounts:change' user_obj.pk %}">Редактировать данные</a><br><br>
                                    <a class="btn btn-outline-success" style="width:350px" href="{% url 'accounts:change_password' user_obj.pk %}">Изменить пароль</a><br><br>
                                    {% if user_obj.is_superuser %}
                                        <a class="btn btn-outline-success" style="width:350px" href="{% url "accounts:register" %}">Зарегистрировать нового пользователя</a><hr>

                                        <button style="width:350px" type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModalA1">
                                           Коэффициент наценки: {{ coefficient.percent }} %
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModalA1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                          <div class="modal-dialog">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Смена статуса заявки</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                              </div>
                                              <div class="modal-body">
                                                <form action="{% url "accounts:coefficient" user_obj.pk %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="form">
                                                        Коэффициент наценки: <p><input type="number" class="form-control" name="percent"></p>
                                                    </div>

                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                                                        <button class="btn btn-primary">Ок</button>
                                                    </div>
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                    {% endif %}
                            </div>
                            {% if user_obj.is_superuser %}
                                <h3>Список сотрудников</h3>
                                {% for user in users %}
                                    {% if not user.is_superuser %}
                                        <a href="{% url "accounts:profile" user.pk %}">
                                            <div style="text-align:center; display: inline-block">
                                                {% if user.profile.avatar %}
                                                    <img style="border-radius: 20px;" src="{{ user.profile.avatar.url }}" width="100" height="100" alt=""><br>
                                                {% else %}
                                                    <img style="border-radius: 20px;" src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-vector-260nw-1725655669.jpg"
                                                           width="100" height="100" alt=""><br>
                                                {% endif %}
                                                {{ user.username }}
                                            </div>
                                        </a>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}

                          </div>
                        </div>
                        <!-- /.card -->
                      </div>
                    </div>
                    <!-- /.row -->
                  </div>
                  <!-- /.container-fluid -->
                </section>
                <!-- /.content -->
              </div>
            </div>
        </div>
    </div>
</div>
<!-- /.card -->
{% endif %}
{% endblock %}

{% block javascripts %}
<!-- jQuery -->
<script src="{% static "assets/plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "assets/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- Select2 -->
<script src="{% static "assets/plugins/select2/js/select2.full.min.js" %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static "assets/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js" %}"></script>
<!-- InputMask -->
<script src="{% static "assets/plugins/moment/moment.min.js" %}"></script>
<script src="{% static "assets/plugins/inputmask/jquery.inputmask.min.js" %}"></script>
<!-- date-range-picker -->
<script src="{% static "assets/plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- bootstrap color picker -->
<script src="{% static "assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Bootstrap Switch -->
<script src="{% static "assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js" %}"></script>
<!-- BS-Stepper -->
<script src="{% static "assets/plugins/bs-stepper/js/bs-stepper.min.js" %}"></script>
<!-- dropzonejs -->
<script src="{% static "assets/plugins/dropzone/min/dropzone.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "assets/dist/js/adminlte.min.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "assets/dist/js/demo.js" %}"></script>
{% endblock %}
