source/sliding_systems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("webapp.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views


app_name = "webapp"

urlpatterns = [
    path('', webapp_views.IndexView.as_view(), name="index"),
    path('gallary/new/', webapp_views.GallaryCreateView.as_view(), name="gallary_create"),
    path('gallary/<int:pk>/delete/', webapp_views.GallaryDeleteView.as_view(), name="gallary_delete"),
    path('products/', webapp_views.ProductView.as_view(), name='product'),
    path('section_add/', webapp_views.SectionAddView.as_view(), name='section_add'),
    path('section/<int:pk>/delete/', webapp_views.SectionDeleteView.as_view(), name='section_del'),
    path('tire_add/', webapp_views.TireAddView.as_view(), name='tire_add'),
    path('tire/<int:pk>/delete/', webapp_views.TireDeleteView.as_view(), name='tire_del'),
    path('glass_add/', webapp_views.GlassAddView.as_view(), name='glass_add'),
    path('glass/<int:pk>/delete/', webapp_views.GlassDeleteView.as_view(), name='glass_del'),
    path('door_knob_add/', webapp_views.DoorKnobAddView.as_view(), name='door_knob_add'),
    path('door_knob/<int:pk>/delete/', webapp_views.DoorKnobDeleteView.as_view(), name='door_knob_del'),
    path('color_add/', webapp_views.ColorAddView.as_view(), name='color_add'),
    path('color/<int:pk>/delete/', webapp_views.ColorDeleteView.as_view(), name='color_del'),
    path('option_add/', webapp_views.OptionAddView.as_view(), name='option_add'),
    path('option/<int:pk>/delete/', webapp_views.OptionDeleteView.as_view(), name='option_del'),
    path('person_add/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('organization_add/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customers/', webapp_views.CustomerListView.as_view(), name='customer_list'),
    path('customer/new/person/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('customer/new/organization/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customer/<int:pk>/', webapp_views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/<int:pk>/delete/', webapp_views.CustomerDeleteView.as_view(), name='customer_del'),
    path('customer/<int:pk>/person_edit/', webapp_views.PersonEditView.as_view(), name='person_edit'),
    path('customer/<int:pk>/organization_edit/', webapp_views.OrganizationEditView.as_view(), name='organization_edit'),
    path('orders/', webapp_views.OrderView.as_view(), name='order'),
    path('order_add/', webapp_views.OrderAddView.as_view(), name='order_add'),
    path('orders/<int:pk>/delete/', webapp_views.OrderDeleteView.as_view(), name='order_del'),
    path('order/<int:pk>/', webapp_views.OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/application/', webapp_views.ApplicationFormView.as_view(), name='application_form'),
    path('order/<int:pk>/application/sliding_system_choice/', webapp_views.ApplicationSlidingSystemChoiceView.as_view(),
         name='application_sliding_system_choice'),
    path('order/<int:pk>/technical_task/', webapp_views.OrderTechnicalTaskView.as_view(), name='technical_task'),
    path('order/<int:pk>/accessories/', webapp_views.OrderAccessoriesView.as_view(), name='accessories'),
    path('order/<int:pk>/status_change/', webapp_views.OrderStatusChangeView.as_view(), name='order_status_change'),
    path('application/<int:pk>/', webapp_views.ApplicationDetailView.as_view(), name='application_detail'),
    path('application/<int:pk>/delete/', webapp_views.ApplicationDeleteView.as_view(), name='application_del'),
    path('application/<int:pk>/edit/', webapp_views.ApplicationEditView.as_view(), name='application_edit'),
    path('mechanism/create/', webapp_views.DetailsCreateView.as_view(), name='mechanism_add'),
    path('mechanism/<int:pk>/delete/', webapp_views.DetailsDeleteView.as_view(), name='mechanism_del'),
    path('mechanismkit/create/', webapp_views.MechanismKitFormView.as_view(), name='mechanismkit_form'),
    path('mechanismkit/<int:pk>/detail_del', webapp_views.MechanismKitFormDetailDeleteView.as_view(),
         name='mechanismkit_detail_del'),
    path('mechanismkit/<int:pk>/detail_add', webapp_views.MechanismKitFormDetailAddView.as_view(),
         name='mechanismkit_detail_add'),
    path('mechanismkit/<int:pk>/delete/', webapp_views.MechanismKitDeleteView.as_view(), name='mechanismkit_del'),
    path('constructor/', webapp_views.ConstructorView.as_view(), name='constructor'),
    path('slidingsystem/create', webapp_views.SlidingSystemFormView.as_view(), name='slidingsystem_add'),
    path('slidingsystem/<int:pk>/delete', webapp_views.SlidingSystemDeleteView.as_view(),
         name='slidingsystem_del'),
    path('slidingsystem/<int:pk>/section_delete', webapp_views.SlidingSystemFormSectionDeleteView.as_view(),
         name='slidingsystem_section_del'),
    path('order/<int:pk>/contract/', webapp_views.OrderContractView.as_view(), name = 'contract'),
    path('order/<int:pk>/commercial_proposal/', webapp_views.OrderCommercialProposalView.as_view(),
         name = 'commercial_proposal'),
]

source/webapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import BaseValidator
from django.utils.deconstruct import deconstructible
from django.utils.translation.trans_null import ngettext_lazy, _


@deconstructible
class DecimalValidator:
    """
    Validate that the input does not exceed the maximum number of digits
    expected, otherwise raise ValidationError.
    """
    messages = {
        'invalid': _('Enter a number.'),
        'max_digits': ngettext_lazy(
            'Количество символов не должно превышать %(max).',
            'Количество символов не должно превышать %(max)',
            'max'
        ),
        'max_decimal_places': ngettext_lazy(
            'Ensure that there are no more than %(max)s decimal place.',
            'Ensure that there are no more than %(max)s decimal places.',
            'max'
        ),
        'max_whole_digits': ngettext_lazy(
            'Ensure that there are no more than %(max)s digit before the decimal point.',
            'Ensure that there are no more than %(max)s digits before the decimal point.',
            'max'
        ),
    }

    def __init__(self, max_digits, decimal_places):
        self.max_digits = max_digits
        self.decimal_places = decimal_places

    def __call__(self, value):
        digit_tuple, exponent = value.as_tuple()[1:]
        if exponent in {'F', 'n', 'N'}:
            raise ValidationError(self.messages['invalid'], code='invalid', params={'value': value})
        if exponent >= 0:
            # A positive exponent adds that many trailing zeros.
            digits = len(digit_tuple) + exponent
            decimals = 0
        else:
            # If the absolute value of the negative exponent is larger than the
            # number of digits, then it's the same as the number of digits,
            # because it'll consume all of the digits in digit_tuple and then
            # add abs(exponent) - len(digit_tuple) leading zeros after the
            # decimal point.
            if abs(exponent) > len(digit_tuple):
                digits = decimals = abs(exponent)
            else:
                digits = len(digit_tuple)
                decimals = abs(exponent)
        whole_digits = digits - decimals

        if self.max_digits is not None and digits > self.max_digits:
            raise ValidationError(
                self.messages['max_digits'],
                code='max_digits',
                params={'max': self.max_digits, 'value': value},
            )
        if self.decimal_places is not None and decimals > self.decimal_places:
            raise ValidationError(
                self.messages['max_decimal_places'],
                code='max_decimal_places',
                params={'max': self.decimal_places, 'value': value},
            )
        if (self.max_digits is not None and self.decimal_places is not None and
                whole_digits > (self.max_digits - self.decimal_places)):
            raise ValidationError(
                self.messages['max_whole_digits'],
                code='max_whole_digits',
                params={'max': (self.max_digits - self.decimal_places), 'value': value},
            )

    def __eq__(self, other):
        return (
            isinstance(other, self.__class__) and
            self.max_digits == other.max_digits and
            self.decimal_places == other.decimal_places
        )


@deconstructible
class MinLengthValidator(BaseValidator):
    message = 'Значение "%(value)" имеет длину %(show_value)! Длина должна быть не менее %(limit_value) символов!'
    code = 'too_short'

    def compare(self, a, b):
        return a < b

    def clean(self, x):
        return len(x)


@deconstructible
class MaxLengthValidator(BaseValidator):
    message = 'Значение "%(value)" имеет длину %(show_value)! Длина должна быть не более %(limit_value) символов!'
    code = 'too_short'

    def compare(self, a, b):
        return a > b

    def clean(self, x):
        return len(x)


class Gallary(models.Model):
    foto = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name="Картинка")
    description = models.TextField(null=True, blank=True, max_length=3000, verbose_name="Описание",
                                   validators=[MaxLengthValidator(3000)])



class Details(models.Model):
    unit_of_measure_choices = [("штук", "штук"), ("комплект", "комплект")]

    image = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name="Картинка")
    name = models.CharField(max_length=150, verbose_name="Наименование детали комплекта механизмов",
                            validators=[MaxLengthValidator(150)])
    unit_of_measure = models.CharField(max_length=50, choices=unit_of_measure_choices, verbose_name="Ед. измерения")
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="Код",
                            validators=[MaxLengthValidator(50)])
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость",
                                validators=[DecimalValidator(7, 0)])
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name="Количество")

    def __str__(self):
        return self.name


class MechanismKitDetail(models.Model):
    unit_of_measure_choices = [("штук", "штук"), ("комплект", "комплект")]

    mechanism_kit = models.ForeignKey("webapp.MechanismKit", on_delete=models.CASCADE,
                                      verbose_name="Комплект механизмов", related_name="details")
    image = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name="Картинка")
    name = models.CharField(max_length=150, verbose_name="Наименование детали комплекта механизмов",
                            validators=[MaxLengthValidator(150)])
    unit_of_measure = models.CharField(max_length=50, choices=unit_of_measure_choices, verbose_name="Ед. измерения")
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="Код",
                            validators=[MaxLengthValidator(50)])
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость",
                                validators=[DecimalValidator(7, 0)])
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name="Количество")

    def __str__(self):
        return self.name


class MechanismKit(models.Model):
    name = models.CharField(max_length=150, verbose_name="Наименование комплекта механизмов",
                            validators=[MaxLengthValidator(150)])
    total = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость комплекта")

    def __str__(self):
        return self.name


class Section(models.Model):
    type_choices = [("без притвора", "без притвора"), ("с притвором", "с притвором"),
                    ("горизонтальный", "горизонтальный")]

    name = models.CharField(max_length=100, verbose_name="Наименование профиля", validators=[MaxLengthValidator(150)])
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="Код",
                            validators=[MaxLengthValidator(50)])
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость профиля",
                                validators=[DecimalValidator(7, 0)])
    type = models.CharField(max_length=20, choices=type_choices, verbose_name="Вид профиля")
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name="Количество")

    def __str__(self):
        return f'{self.name} - {self.type}'


class SlidingSystemSection(models.Model):
    type_choices = [("без притвора", "без притвора"), ("с притвором", "с притвором"),
                    ("горизонтальный", "горизонтальный")]

    sliding_system = models.ForeignKey("webapp.SlidingSystem", on_delete=models.CASCADE,
                                      verbose_name="Комплект механизмов", related_name="sections")
    name = models.CharField(max_length=100, verbose_name="Наименование профиля", validators=[MaxLengthValidator(100)])
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="Код",
                            validators=[MaxLengthValidator(50)])
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость профиля",
                                validators=[DecimalValidator(7, 0)])
    type = models.CharField(max_length=20, choices=type_choices, verbose_name="Вид профиля")
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name="Количество")
    quantity_sash = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name="Количество балок")

    def __str__(self):
        return f'{self.name} - {self.type}'


class Tire(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование шины", validators=[MaxLengthValidator(100)])
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="Код",
                            validators=[MaxLengthValidator(50)])
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Стоимость шины",
                                validators=[DecimalValidator(7, 0)])
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name="Количество шины")
    width = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name="Длинна шины")

    def __str__(self):
        return self.name


class SlidingSystem(models.Model):
    type_choices = [("в нишу", "в нишу"), ("на нишу", "на нишу")]

source/webapp/views/frame_view.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, DeleteView
from webapp.models import Frame


class FrameView(ListView):
    model = Frame
    template_name = 'constructor/constructor_list.html'


class FrameCreateView(CreateView):
    model = Frame
    fields = ["type", "profile_sash", "profile_sash_width", "quantity", "price_profile_sash_vertical",  "price_profile_sash_top_bottom"]
    template_name = 'constructor/frame_create.html'

    def get_success_url(self):
        return reverse('webapp:constructor')


class FrameDeleteView(DeleteView):
    model = Frame
    template_name = 'constructor/constructor_list.html'

    def get_success_url(self):
        return reverse('webapp:constructor')

source/webapp/views/gallary_view.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, DeleteView
from webapp.models import Gallary


class IndexView(ListView):
    model = Gallary
    template_name = "index.html"
    paginate_by = 8


class GallaryCreateView(CreateView):
    model = Gallary
    fields = ["foto", "description"]
    template_name = "gallary/create.html"

    def get_success_url(self):
        return reverse("webapp:index")


class GallaryDeleteView(DeleteView):
    model = Gallary
    template_name = "index.html"

    def get_success_url(self):
        return reverse("webapp:index")

source/webapp/templates/constructor/slidingsystem_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block title %} Добавить "Раздвижную систему" {% endblock %}

<!-- Element injected in the BODY element -->
{% block body_class %} {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "assets/plugins/fontawesome-free/css/all.min.css" %}>
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "assets/css/adminlte.min.css" %}">

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Добавить "Раздвижную систему"</h1>
                    </div>
                    <div class="col-sm-6">
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div>
                                    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal1">
                                      Добавить профиль
                                    </button>

                                        <!-- Modal -->
                                      <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                          <div class="modal-dialog modal-lg">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Добавить </h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                              </div>
                                              <div class="modal-body">
                                                    <table class="table">
                                                      <thead>
                                                        <tr>
                                                          <th scope="col">Наименование</th>
                                                          <th scope="col">Ед. измерения</th>
                                                          <th scope="col">Код</th>
                                                        </tr>
                                                      </thead>
                                                      {% for section in sections %}
                                                          <div style="font-size: 17px; margin-top:10px;">
                                                              <tbody>
                                                                <tr>
                                                                  <td>{{ section.name }}, {{ section.type }}</td>
                                                                  <td>хлыст 6м</td>
                                                                  <td>{{ section.code }}</td>
                                                                  <td>
                                                                    <form action="{% url "webapp:slidingsystem_add" %}" method="post">
                                                                       {% csrf_token %}
                                                                       <button name="section_id" value="{{ section.id }}" class="btn btn-primary btn-success">Добавить</button>
                                                                    </form>
                                                                  </td>
                                                                </tr>
                                                              </tbody>
                                                          </div>
                                                      {% endfor %}
                                                    </table>
                                              </div>
                                              <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                                              </div>
                                            </div>
                                          </div>
                                      </div>
                                </div><hr>

                                <div>
                                    <table class="table">
                                      <thead>
                                        <tr>
                                          <th scope="col">Наименование</th>
                                          <th scope="col">Ед. измерения</th>
                                          <th scope="col">Код</th>
                                          <th scope="col">Удалить</th>
                                        </tr>
                                      </thead>
                                        {% for section in section_list %}
                                            <div style="margin: 20px;">
                                                <tbody>
                                                    <tr>
                                                      <td>{{ section.name }}, {{ section.type }}</td>
                                                      <td>хлыст 6м</td>
                                                      <td>{{ detail.code }}</td>
                                                      <td>
                                                          <form style="display: inline-block;"
                                                              action="{% url "webapp:slidingsystem_section_del" section.pk %}" method="post">
                                                             {% csrf_token %}
                                                             <button class="btn btn-outline-danger">-</button>
                                                          </form>
                                                      </td>
                                                    </tr>
                                                </tbody>
                                            </div>
                                        {% endfor %}
                                    </table>
                                </div>
                                <form style="margin: 20px;" action="{% url 'webapp:constructor' %} " method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button name="sliding_system" value="sliding_system" class="btn btn-dark">Создать "Раздвижную систему"</button>
                                </form>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>


{% endif %}
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <!-- jQuery -->
    <script src="{% static "assets/plugins/jquery/jquery.min.js"  %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static "assets/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <!-- DataTables -->
    <script src="{% static "assets/plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js" %}"></script>
    <script src="{% static "assets/plugins/datatables-responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js" %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static "assets/js/adminlte.min.js" %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static "assets/js/demo.js" %}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

{% endblock javascripts %}
