source/accounts/urls.py
from django.urls import path, include
from accounts import views as account_views


app_name = "accounts"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("create/", account_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", account_views.UserDetailView.as_view(), name="profile"),
    path('<int:pk>/change/', account_views.UserChangeView.as_view(), name='change'),
    path("<int:pk>/change-password/", account_views.UserPasswordChangeView.as_view(), name="change_password"),
    path("<int:pk>/coefficient/", account_views.CoefficientAddView.as_view(), name="coefficient")
]

source/sliding_systems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("webapp.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views


app_name = "webapp"

urlpatterns = [
    path('', webapp_views.IndexView.as_view(), name="index"),
    path('gallary/new/', webapp_views.GallaryCreateView.as_view(), name="gallary_create"),
    path('gallary/<int:pk>/delete/', webapp_views.GallaryDeleteView.as_view(), name="gallary_delete"),
    path('products/', webapp_views.ProductView.as_view(), name='product'),
    path('section_add/', webapp_views.SectionAddView.as_view(), name='section_add'),
    path('section/<int:pk>/delete/', webapp_views.SectionDeleteView.as_view(), name='section_del'),
    path('tire_add/', webapp_views.TireAddView.as_view(), name='tire_add'),
    path('tire/<int:pk>/delete/', webapp_views.TireDeleteView.as_view(), name='tire_del'),
    path('glass_add/', webapp_views.GlassAddView.as_view(), name='glass_add'),
    path('glass/<int:pk>/delete/', webapp_views.GlassDeleteView.as_view(), name='glass_del'),
    path('door_knob_add/', webapp_views.DoorKnobAddView.as_view(), name='door_knob_add'),
    path('door_knob/<int:pk>/delete/', webapp_views.DoorKnobDeleteView.as_view(), name='door_knob_del'),
    path('color_add/', webapp_views.ColorAddView.as_view(), name='color_add'),
    path('color/<int:pk>/delete/', webapp_views.ColorDeleteView.as_view(), name='color_del'),
    path('option_add/', webapp_views.OptionAddView.as_view(), name='option_add'),
    path('option/<int:pk>/delete/', webapp_views.OptionDeleteView.as_view(), name='option_del'),
    path('person_add/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('organization_add/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customers/', webapp_views.CustomerListView.as_view(), name='customer_list'),
    path('customer/new/person/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('customer/new/organization/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customer/<int:pk>/', webapp_views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/<int:pk>/delete/', webapp_views.CustomerDeleteView.as_view(), name='customer_del'),
    path('customer/<int:pk>/person_edit/', webapp_views.PersonEditView.as_view(), name='person_edit'),
    path('customer/<int:pk>/organization_edit/', webapp_views.OrganizationEditView.as_view(), name='organization_edit'),
    path('orders/', webapp_views.OrderView.as_view(), name='order'),
    path('order_add/', webapp_views.OrderAddView.as_view(), name='order_add'),
    path('orders/<int:pk>/delete/', webapp_views.OrderDeleteView.as_view(), name='order_del'),
    path('order/<int:pk>/', webapp_views.OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/application/', webapp_views.ApplicationFormView.as_view(), name='application_form'),
    path('order/<int:pk>/application/sliding_system_choice/', webapp_views.ApplicationSlidingSystemChoiceView.as_view(),
         name='application_sliding_system_choice'),
    path('order/<int:pk>/technical_task/', webapp_views.OrderTechnicalTaskView.as_view(), name='technical_task'),
    path('order/<int:pk>/accessories/', webapp_views.OrderAccessoriesView.as_view(), name='accessories'),
    path('order/<int:pk>/status_change/', webapp_views.OrderStatusChangeView.as_view(), name='order_status_change'),
    path('application/<int:pk>/', webapp_views.ApplicationDetailView.as_view(), name='application_detail'),
    path('application/<int:pk>/delete/', webapp_views.ApplicationDeleteView.as_view(), name='application_del'),
    path('application/<int:pk>/edit/', webapp_views.ApplicationEditView.as_view(), name='application_edit'),
    path('mechanism/create/', webapp_views.DetailsCreateView.as_view(), name='mechanism_add'),
    path('mechanism/<int:pk>/delete/', webapp_views.DetailsDeleteView.as_view(), name='mechanism_del'),
    path('mechanismkit/create/', webapp_views.MechanismKitFormView.as_view(), name='mechanismkit_form'),
    path('mechanismkit/<int:pk>/detail_del', webapp_views.MechanismKitFormDetailDeleteView.as_view(),
         name='mechanismkit_detail_del'),
    path('mechanismkit/<int:pk>/detail_add', webapp_views.MechanismKitFormDetailAddView.as_view(),
         name='mechanismkit_detail_add'),
    path('mechanismkit/<int:pk>/delete/', webapp_views.MechanismKitDeleteView.as_view(), name='mechanismkit_del'),
    path('constructor/', webapp_views.ConstructorView.as_view(), name='constructor'),
    path('slidingsystem/create', webapp_views.SlidingSystemFormView.as_view(), name='slidingsystem_add'),
    path('slidingsystem/<int:pk>/delete', webapp_views.SlidingSystemDeleteView.as_view(),
         name='slidingsystem_del'),
    path('slidingsystem/<int:pk>/section_delete', webapp_views.SlidingSystemFormSectionDeleteView.as_view(),
         name='slidingsystem_section_del'),
    path('order/<int:pk>/contract/', webapp_views.OrderContractView.as_view(), name = 'contract'),
    path('order/<int:pk>/commercial_proposal/', webapp_views.OrderCommercialProposalView.as_view(),
         name = 'commercial_proposal'),
]

source/webapp/views/application_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import View, DetailView, UpdateView
from django.shortcuts import get_object_or_404, render
from webapp.models import Application, Order, SlidingSystem
from webapp.forms import ApplicationForm, ApplicationForm2


class ApplicationSlidingSystemChoiceView(View):
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_systems = SlidingSystem.objects.all()
        return render(request, "application/application_sliding_systems_choice.html",
                      {"order": order, "sliding_systems": sliding_systems})

    def post(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_systems = SlidingSystem.objects.all()
        return render(request, "application/application_sliding_systems_choice.html",
                      {"order": order, "sliding_systems": sliding_systems})


class ApplicationFormView(View):
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_system = get_object_or_404(SlidingSystem, pk=request.GET.get("sliding_system_id"))
        if sliding_system.door_knob == "есть":
            form = ApplicationForm
        else:
            form = ApplicationForm2
        return render(request, "application/application_form.html",
                      {"order": order, "form": form, "sliding_system": sliding_system})

    def post(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_system = get_object_or_404(SlidingSystem, pk=request.GET.get("sliding_system_id"))
        if sliding_system.door_knob == "есть":
            form = ApplicationForm
        else:
            form = ApplicationForm2
        return render(request, "application/application_form.html",
                      {"order": order, "form": form, "sliding_system": sliding_system})


class ApplicationDetailView(DetailView):
    model = Application
    template_name = "application/application_detail.html"


class ApplicationDeleteView(PermissionRequiredMixin, View):
    permission_required = "webapp.delete_application"

    def post(self, request, *args, **kwargs):
        application = get_object_or_404(Application, pk=kwargs["pk"])
        order = application.order
        application.summa = application.summa + ((application.summa / 100) * 3)
        order.summa = int(order.summa) - int(application.summa)
        order.save()
        application.delete()
        return render(request, "order/order_detail.html", {"order": order})


class ApplicationEditView(PermissionRequiredMixin, UpdateView):
    model = Application
    fields = ["sliding_system", "color", "glass", "door_knob", "option", "width",
              "height", "direction", "address", "loaders_price", "lift"]
    template_name = 'application/application_edit.html'
    permission_required = "webapp.change_application"

    def get_success_url(self):
        return reverse("webapp:application_detail", kwargs={"pk": self.get_object().pk})

source/webapp/views/constructor_view.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DeleteView

from webapp.forms import MechanismKitForm, SlidingSystemForm
from webapp.models import SlidingSystem, MechanismKit, MechanismKitDetail, Details, Section, SlidingSystemSection
from webapp.views import MechanismBuffer


class ConstructorView(View):
    def get(self, request, *args, **kwargs):
        sliding_systems = SlidingSystem.objects.all()
        mechanismkit_list = MechanismKit.objects.all()
        MechanismBuffer.total = 0
        MechanismBuffer.details_list = []
        SectionBuffer.section_list = []
        return render(request, "constructor/constructor_list.html",
                      {"mechanismkit_list": mechanismkit_list, "slidingsystem_list": sliding_systems})

    def post(self, request, *args, **kwargs):
        sliding_systems = SlidingSystem.objects.all()
        mechanismkit_list = MechanismKit.objects.all()
        if request.POST.get("mechanismkit") == "mechanismkit":
            form = MechanismKitForm(data=request.POST)
            if form.is_valid():
                mechanismkit = MechanismKit.objects.create(
                    name=form.cleaned_data["name"],
                    total=int(MechanismBuffer.total))
                for detail in MechanismBuffer.details_list:
                    MechanismKitDetail.objects.create(
                        mechanism_kit=mechanismkit,
                        image=detail.image,
                        name=detail.name,
                        unit_of_measure=detail.unit_of_measure,
                        code=detail.code,
                        price=detail.price,
                        quantity=detail.quantity)
            MechanismBuffer.total = 0
            MechanismBuffer.details_list = []
            for m_detail in Details.objects.all():
                m_detail.quantity = 1
                m_detail.save()
        if request.POST.get("sliding_system") == "sliding_system":
            form = SlidingSystemForm(request.POST, request.FILES)
            if form.is_valid():
                sliding_system = SlidingSystem.objects.create(
                    image=form.cleaned_data["image"],
                    name=form.cleaned_data["name"],
                    frame_quantity=form.cleaned_data["frame_quantity"],
                    coupler_quantity=form.cleaned_data["coupler_quantity"],
                    mechanism_kit=form.cleaned_data["mechanism_kit"],
                    tire=form.cleaned_data["tire"],
                    type=form.cleaned_data["type"],
                    drive=form.cleaned_data["drive"],
                    door_knob=form.cleaned_data["door_knob"])
                for section in SectionBuffer.section_list:
                    SlidingSystemSection.objects.create(
                        sliding_system=sliding_system,
                        name=section.name,
                        type=section.type,
                        code=section.code,
                        price=section.price,
                        quantity=section.quantity)
            SectionBuffer.section_list = []
        return render(request, "constructor/constructor_list.html",
                      {"mechanismkit_list": mechanismkit_list, "slidingsystem_list": sliding_systems})


class SectionBuffer:
    section_list = []


class SlidingSystemFormView(View):
    permission_required = "webapp.add_slidingsystem"
    def get(self, request, *args, **kwargs):
        form = SlidingSystemForm
        sections = Section.objects.all()
        return render(request, "constructor/slidingsystem_form.html",
                      {"form": form, "sections": sections, "section_list": SectionBuffer.section_list})

    def post(self, request, *args, **kwargs):
        form = SlidingSystemForm
        section = get_object_or_404(Section, pk=int(request.POST.get("section_id")))
        if section not in SectionBuffer.section_list:
            SectionBuffer.section_list.append(section)
        sections = Section.objects.all()
        return render(request, "constructor/slidingsystem_form.html",
                      {"form": form, "sections": sections, "section_list": SectionBuffer.section_list})


class SlidingSystemDeleteView(DeleteView):
    model = SlidingSystem
    template_name = 'constructor/constructor_list.html'
    permission_required = "webapp.delete_slidingsystem"

    def get_success_url(self):
        return reverse('webapp:constructor')


class SlidingSystemFormSectionDeleteView(View):
    def post(self, request, *args, **kwargs):
        section = get_object_or_404(Section, pk=kwargs["pk"])
        if section in SectionBuffer.section_list:
            SectionBuffer.section_list.remove(section)
        form = MechanismKitForm
        sections = Section.objects.all()
        return render(request, "constructor/slidingsystem_form.html",
                      {"form": form, "sections": sections, "section_list": SectionBuffer.section_list})

source/webapp/views/customer_view.py
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from webapp.forms import SearchForm
from webapp.models import Customer


class CustomerListView(ListView):
    model = Customer
    template_name = "customer/customer_list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"q": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value) | Q(organization_name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["q"]

class PersonCreateView(CreateView):
    model = Customer
    fields = ["name", "phone", "address", "iin", "identification"]
    template_name = "customer/person_add.html"
    permission_required = "webapp.add_customer"

    def get_success_url(self):
        return reverse("webapp:customer_list")


class OrganizationCreateView(CreateView):
    model = Customer
    fields = ["name", "organization_name", "phone", "address", "bin", "iban"]
    template_name = "customer/organization_add.html"

    def get_success_url(self):
        return reverse("webapp:customer_list")


class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = 'customer/customer_list.html'
    success_url = reverse_lazy('webapp:customer_list')
    permission_required = "webapp.delete_customer"


class PersonEditView(UpdateView):
    model = Customer
    fields = ["name", "phone", "address", "iin", "identification"]
    template_name = 'customer/person_edit.html'
    permission_required = "webapp.change_customer"

    def get_success_url(self):
        return reverse("webapp:customer_list")


class OrganizationEditView(UpdateView):
    model = Customer
    fields = ["organization_name", "name", "phone", "address", "bin", "iban"]
    template_name = 'customer/organization_edit.html'

    def get_success_url(self):
        return reverse("webapp:customer_list")


class CustomerDetailView(DetailView):
    model = Customer
    template_name = 'customer/customer_detail.html'

source/webapp/templates/includes/footer.html
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    &copy; <a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/artedellaporta.kz/">https://www.instagram.com/artedellaporta.kz/</a>
  </footer>

source/webapp/templates/includes/navigation.html
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url "webapp:index" %}" class="nav-link">Главная</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url "webapp:customer_list" %}" class="nav-link">Контрагенты</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url "webapp:product" %}" class="nav-link">Компоненты</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url "webapp:constructor" %}" class="nav-link">Конструктор</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url "webapp:order" %}" class="nav-link">Заявки</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
{#    <form class="form-inline ml-3">#}
{#      <div class="input-group input-group-sm">#}
{#        <input class="form-control form-cotrol-navbar" type="search" placeholder="Поиск" aria-label="Поиск">#}
{#        <div class="input-group-append">n#}
{#          <button class="btn btn-navbar" type="submit">#}
{#            <i class="fas fa-search"></i>#}
{#          </button>#}
{#        </div>#}
{#      </div>#}
{#    </form>#}
  </nav>
  <!-- /.navbar -->

source/webapp/templates/includes/sidebar.html
{% if user.is_authenticated %}
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url "webapp:index" %}" class="brand-link">
      <img src="/uploads/img/Logo1.png" alt="Logo" style="width: 230px; height: 50px;">
      <span class="brand-text font-weight-light"></span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            {% if request.user.profile.avatar %}
                <img style="width: 40px; height: 40px" src="{{ request.user.profile.avatar.url }}" class="img-circle elevation-2" alt="User Image">
            {% else %}
                <img style="width: 40px; height: 40px" src="/uploads/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            {% endif %}
        </div>
        <div class="info">
          <a href="{% url "accounts:profile" user.pk %}" class="d-block">
            {{ request.user.username }}
          </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{% url "webapp:customer_list" %}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                      <p>Контрагенты</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "webapp:product" %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Компоненты</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "webapp:constructor" %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Конструктор</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "webapp:order" %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Заявки</p>
                    </a>
                </li>
        </ul>
        <form style="margin-top: 100px; margin-left: 20px" action="{% url "accounts:logout" %}" method="post">
            {% csrf_token %}
            <button class="btn btn-secondary">Выйти</button>
        </form>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
{% else %}

{% endif %}
  