source/sliding_systems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("webapp.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


source/webapp/urls.py
from django.urls import path
from webapp import views as webapp_views


app_name = "webapp"

urlpatterns = [
    path('', webapp_views.IndexView.as_view(), name="index"),
    path('gallary/new/', webapp_views.GallaryCreateView.as_view(), name="gallary_create"),
    path('gallary/<int:pk>/delete/', webapp_views.GallaryDeleteView.as_view(), name="gallary_delete"),
    path('products/', webapp_views.ProductView.as_view(), name='product'),
    path('section_add/', webapp_views.SectionAddView.as_view(), name='section_add'),
    path('section/<int:pk>/delete/', webapp_views.SectionDeleteView.as_view(), name='section_del'),
    path('tire_add/', webapp_views.TireAddView.as_view(), name='tire_add'),
    path('tire/<int:pk>/delete/', webapp_views.TireDeleteView.as_view(), name='tire_del'),
    path('glass_add/', webapp_views.GlassAddView.as_view(), name='glass_add'),
    path('glass/<int:pk>/delete/', webapp_views.GlassDeleteView.as_view(), name='glass_del'),
    path('door_knob_add/', webapp_views.DoorKnobAddView.as_view(), name='door_knob_add'),
    path('door_knob/<int:pk>/delete/', webapp_views.DoorKnobDeleteView.as_view(), name='door_knob_del'),
    path('color_add/', webapp_views.ColorAddView.as_view(), name='color_add'),
    path('color/<int:pk>/delete/', webapp_views.ColorDeleteView.as_view(), name='color_del'),
    path('option_add/', webapp_views.OptionAddView.as_view(), name='option_add'),
    path('option/<int:pk>/delete/', webapp_views.OptionDeleteView.as_view(), name='option_del'),
    path('person_add/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('organization_add/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customers/', webapp_views.CustomerListView.as_view(), name='customer_list'),
    path('customer/new/person/', webapp_views.PersonCreateView.as_view(), name='person_add'),
    path('customer/new/organization/', webapp_views.OrganizationCreateView.as_view(), name='organization_add'),
    path('customer/<int:pk>/', webapp_views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/<int:pk>/delete/', webapp_views.CustomerDeleteView.as_view(), name='customer_del'),
    path('customer/<int:pk>/person_edit/', webapp_views.PersonEditView.as_view(), name='person_edit'),
    path('customer/<int:pk>/organization_edit/', webapp_views.OrganizationEditView.as_view(), name='organization_edit'),
    path('orders/', webapp_views.OrderView.as_view(), name='order'),
    path('order_add/', webapp_views.OrderAddView.as_view(), name='order_add'),
    path('orders/<int:pk>/delete/', webapp_views.OrderDeleteView.as_view(), name='order_del'),
    path('order/<int:pk>/', webapp_views.OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/application/', webapp_views.ApplicationFormView.as_view(), name='application_form'),
    path('order/<int:pk>/application/sliding_system_choice/', webapp_views.ApplicationSlidingSystemChoiceView.as_view(),
         name='application_sliding_system_choice'),
    path('order/<int:pk>/technical_task/', webapp_views.OrderTechnicalTaskView.as_view(), name='technical_task'),
    path('order/<int:pk>/accessories/', webapp_views.OrderAccessoriesView.as_view(), name='accessories'),
    path('order/<int:pk>/status_change/', webapp_views.OrderStatusChangeView.as_view(), name='order_status_change'),
    path('application/<int:pk>/', webapp_views.ApplicationDetailView.as_view(), name='application_detail'),
    path('application/<int:pk>/delete/', webapp_views.ApplicationDeleteView.as_view(), name='application_del'),
    path('application/<int:pk>/edit/', webapp_views.ApplicationEditView.as_view(), name='application_edit'),
    path('mechanism/create/', webapp_views.DetailsCreateView.as_view(), name='mechanism_add'),
    path('mechanism/<int:pk>/delete/', webapp_views.DetailsDeleteView.as_view(), name='mechanism_del'),
    path('mechanismkit/create/', webapp_views.MechanismKitFormView.as_view(), name='mechanismkit_form'),
    path('mechanismkit/<int:pk>/detail_del', webapp_views.MechanismKitFormDetailDeleteView.as_view(),
         name='mechanismkit_detail_del'),
    path('mechanismkit/<int:pk>/detail_add', webapp_views.MechanismKitFormDetailAddView.as_view(),
         name='mechanismkit_detail_add'),
    path('mechanismkit/<int:pk>/delete/', webapp_views.MechanismKitDeleteView.as_view(), name='mechanismkit_del'),
    path('constructor/', webapp_views.ConstructorView.as_view(), name='constructor'),
    path('slidingsystem/create', webapp_views.SlidingSystemFormView.as_view(), name='slidingsystem_add'),
    path('slidingsystem/<int:pk>/delete', webapp_views.SlidingSystemDeleteView.as_view(),
         name='slidingsystem_del'),
    path('slidingsystem/<int:pk>/section_delete', webapp_views.SlidingSystemFormSectionDeleteView.as_view(),
         name='slidingsystem_section_del'),
    path('order/<int:pk>/contract/', webapp_views.OrderContractView.as_view(), name = 'contract'),
    path('order/<int:pk>/commercial_proposal/', webapp_views.OrderCommercialProposalView.as_view(),
         name = 'commercial_proposal'),
]

source/webapp/views/application_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import View, DetailView, UpdateView
from django.shortcuts import get_object_or_404, render
from webapp.models import Application, Order, SlidingSystem
from webapp.forms import ApplicationForm, ApplicationForm2


class ApplicationSlidingSystemChoiceView(View):
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_systems = SlidingSystem.objects.all()
        return render(request, "application/application_sliding_systems_choice.html",
                      {"order": order, "sliding_systems": sliding_systems})

    def post(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_systems = SlidingSystem.objects.all()
        return render(request, "application/application_sliding_systems_choice.html",
                      {"order": order, "sliding_systems": sliding_systems})


class ApplicationFormView(View):
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_system = get_object_or_404(SlidingSystem, pk=request.GET.get("sliding_system_id"))
        if sliding_system.door_knob == "есть":
            form = ApplicationForm
        else:
            form = ApplicationForm2
        return render(request, "application/application_form.html",
                      {"order": order, "form": form, "sliding_system": sliding_system})

    def post(self, request, *args, **kwargs):
        order = get_object_or_404(Order, pk=kwargs["pk"])
        sliding_system = get_object_or_404(SlidingSystem, pk=request.GET.get("sliding_system_id"))
        if sliding_system.door_knob == "есть":
            form = ApplicationForm
        else:
            form = ApplicationForm2
        return render(request, "application/application_form.html",
                      {"order": order, "form": form, "sliding_system": sliding_system})


class ApplicationDetailView(DetailView):
    model = Application
    template_name = "application/application_detail.html"


class ApplicationDeleteView(PermissionRequiredMixin, View):
    permission_required = "webapp.delete_application"

    def post(self, request, *args, **kwargs):
        application = get_object_or_404(Application, pk=kwargs["pk"])
        order = application.order
        application.summa = application.summa + ((application.summa / 100) * 3)
        order.summa = int(order.summa) - int(application.summa)
        order.save()
        application.delete()
        return render(request, "order/order_detail.html", {"order": order})


class ApplicationEditView(PermissionRequiredMixin, UpdateView):
    model = Application
    fields = ["sliding_system", "color", "glass", "door_knob", "option", "width",
              "height", "direction", "address", "loaders_price", "lift"]
    template_name = 'application/application_edit.html'
    permission_required = "webapp.change_application"

    def get_success_url(self):
        return reverse("webapp:application_detail", kwargs={"pk": self.get_object().pk})

source/webapp/views/constructor_view.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DeleteView

from webapp.forms import MechanismKitForm, SlidingSystemForm
from webapp.models import SlidingSystem, MechanismKit, MechanismKitDetail, Details, Section, SlidingSystemSection
from webapp.views import MechanismBuffer


class ConstructorView(View):
    def get(self, request, *args, **kwargs):
        sliding_systems = SlidingSystem.objects.all()
        mechanismkit_list = MechanismKit.objects.all()
        MechanismBuffer.total = 0
        MechanismBuffer.details_list = []
        SectionBuffer.section_list = []
        return render(request, "constructor/constructor_list.html",
                      {"mechanismkit_list": mechanismkit_list, "slidingsystem_list": sliding_systems})

    def post(self, request, *args, **kwargs):
        sliding_systems = SlidingSystem.objects.all()
        mechanismkit_list = MechanismKit.objects.all()
        if request.POST.get("mechanismkit") == "mechanismkit":
            form = MechanismKitForm(data=request.POST)
            if form.is_valid():
                mechanismkit = MechanismKit.objects.create(
                    name=form.cleaned_data["name"],
                    total=int(MechanismBuffer.total))
                for detail in MechanismBuffer.details_list:
                    MechanismKitDetail.objects.create(
                        mechanism_kit=mechanismkit,
                        image=detail.image,
                        name=detail.name,
                        unit_of_measure=detail.unit_of_measure,
                        code=detail.code,
                        price=detail.price,
                        quantity=detail.quantity)
            MechanismBuffer.total = 0
            MechanismBuffer.details_list = []
            for m_detail in Details.objects.all():
                m_detail.quantity = 1
                m_detail.save()
        if request.POST.get("sliding_system") == "sliding_system":
            form = SlidingSystemForm(request.POST, request.FILES)
            if form.is_valid():
                sliding_system = SlidingSystem.objects.create(
                    image=form.cleaned_data["image"],
                    name=form.cleaned_data["name"],
                    frame_quantity=form.cleaned_data["frame_quantity"],
                    coupler_quantity=form.cleaned_data["coupler_quantity"],
                    mechanism_kit=form.cleaned_data["mechanism_kit"],
                    tire=form.cleaned_data["tire"],
                    type=form.cleaned_data["type"],
                    drive=form.cleaned_data["drive"],
                    door_knob=form.cleaned_data["door_knob"])
                for section in SectionBuffer.section_list:
                    SlidingSystemSection.objects.create(
                        sliding_system=sliding_system,
                        name=section.name,
                        type=section.type,
                        code=section.code,
                        price=section.price,
                        quantity=section.quantity)
            SectionBuffer.section_list = []
        return render(request, "constructor/constructor_list.html",
                      {"mechanismkit_list": mechanismkit_list, "slidingsystem_list": sliding_systems})


class SectionBuffer:
    section_list = []


class SlidingSystemFormView(View):
    permission_required = "webapp.add_slidingsystem"
    def get(self, request, *args, **kwargs):
        form = SlidingSystemForm
        sections = Section.objects.all()
        return render(request, "constructor/slidingsystem_form.html",
                      {"form": form, "sections": sections, "section_list": SectionBuffer.section_list})

    def post(self, request, *args, **kwargs):
        form = SlidingSystemForm
        section = get_object_or_404(Section, pk=int(request.POST.get("section_id")))
        if section not in SectionBuffer.section_list:
            SectionBuffer.section_list.append(section)
        sections = Section.objects.all()
        return render(request, "constructor/slidingsystem_form.html",
                      {"form": form, "sections": sections, "section_list": SectionBuffer.section_list})


class SlidingSystemDeleteView(DeleteView):
    model = SlidingSystem
    template_name = 'constructor/constructor_list.html'
    permission_required = "webapp.delete_slidingsystem"

    def get_success_url(self):
        return reverse('webapp:constructor')


class SlidingSystemFormSectionDeleteView(View):
    def post(self, request, *args, **kwargs):
        section = get_object_or_404(Section, pk=kwargs["pk"])
        if section in SectionBuffer.section_list:
            SectionBuffer.section_list.remove(section)
        form = MechanismKitForm
        sections = Section.objects.all()
        return render(request, "constructor/slidingsystem_form.html",
                      {"form": form, "sections": sections, "section_list": SectionBuffer.section_list})

source/webapp/views/customer_view.py
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from webapp.forms import SearchForm
from webapp.models import Customer


class CustomerListView(ListView):
    model = Customer
    template_name = "customer/customer_list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["query"] = urlencode({"q": self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value) | Q(organization_name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["q"]

class PersonCreateView(CreateView):
    model = Customer
    fields = ["name", "phone", "address", "iin", "identification"]
    template_name = "customer/person_add.html"
    permission_required = "webapp.add_customer"

    def get_success_url(self):
        return reverse("webapp:customer_list")


class OrganizationCreateView(CreateView):
    model = Customer
    fields = ["name", "organization_name", "phone", "address", "bin", "iban"]
    template_name = "customer/organization_add.html"

    def get_success_url(self):
        return reverse("webapp:customer_list")


class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = 'customer/customer_list.html'
    success_url = reverse_lazy('webapp:customer_list')
    permission_required = "webapp.delete_customer"


class PersonEditView(UpdateView):
    model = Customer
    fields = ["name", "phone", "address", "iin", "identification"]
    template_name = 'customer/person_edit.html'
    permission_required = "webapp.change_customer"

    def get_success_url(self):
        return reverse("webapp:customer_list")


class OrganizationEditView(UpdateView):
    model = Customer
    fields = ["organization_name", "name", "phone", "address", "bin", "iban"]
    template_name = 'customer/organization_edit.html'

    def get_success_url(self):
        return reverse("webapp:customer_list")


class CustomerDetailView(DetailView):
    model = Customer
    template_name = 'customer/customer_detail.html'

source/webapp/views/frame_view.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, DeleteView
from webapp.models import Frame


class FrameView(ListView):
    model = Frame
    template_name = 'constructor/constructor_list.html'


class FrameCreateView(CreateView):
    model = Frame
    fields = ["type", "profile_sash", "profile_sash_width", "quantity", "price_profile_sash_vertical",  "price_profile_sash_top_bottom"]
    template_name = 'constructor/frame_create.html'

    def get_success_url(self):
        return reverse('webapp:constructor')


class FrameDeleteView(DeleteView):
    model = Frame
    template_name = 'constructor/constructor_list.html'

    def get_success_url(self):
        return reverse('webapp:constructor')

source/webapp/templates/customer/customer_list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Контрагенты {% endblock %}

<!-- Element injected in the BODY element -->
{% block body_class %} {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "assets/plugins/fontawesome-free/css/all.min.css" %}>
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "assets/css/adminlte.min.css" %}">

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Контрагенты</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item">
                                {% if perms.webapp.add_customer %}
                                    <a style="display:inline-block" id="btnGroupDrop1" type="button" class="btn dropdown-toggle p-0" data-bs-toggle="dropdown" aria-expanded="false">
                                        Добавить
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                        <a style="width: 350px;" class="dropdown-item" href="{% url "webapp:person_add" %}">Частное лицо</a>
                                        <a class="dropdown-item" href="{% url "webapp:organization_add" %}">Организация</a>
                                    </ul>
                                {% endif %}
                            </li>
                            <li class="breadcrumb-item active">Контрагенты</li>
                        </ol>
                    </div>
                </div>
                {% include "partial/search_form.html" %}
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example2" style="text-align: center" class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>Наименование</th>
                                            <th>Телефон</th>
                                            <th>Адрес</th>
                                            <th>ИИН/БИН</th>
                                            <th>№паспорта/р.с.</th>
                                            <th>Редактировать</th>
                                            <th>Удалить</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for customer in customer_list %}
                                        <tr>
                                            <td>
                                                <a href="{% url "webapp:customer_detail" customer.id %}" class="link-black">
                                                    {{ customer.name }}
                                                </a>
                                            </td>
                                            <td>{{ customer.phone }}</td>
                                            <td>{{ customer.address }}</td>
                                            <td>
                                            {% if customer.iin %}
                                                {{ customer.iin }}
                                            {% else %}
                                                {{ customer.bin }}
                                            {% endif %}
                                            </td>
                                            <td>
                                                {% if customer.identification %}
                                                    {{ customer.identification }}
                                                {% else %}
                                                    {{ customer.iban }}
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if perms.webapp.change_customer %}
                                                    {% if customer.iin %}
                                                        <a class="btn btn-outline-primary" href="{% url "webapp:person_edit" customer.pk %}">
                                                            <i class="bi bi-pencil-fill "></i>
                                                        </a>
                                                    {% else %}
                                                         <a class="btn btn-outline-primary" href="{% url "webapp:organization_edit" customer.pk %}">
                                                              <i class="bi bi-pencil-fill"></i>
                                                         </a>
                                                    {% endif %}
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if perms.webapp.delete_customer %}
                                                    <form action="{% url "webapp:customer_del" customer.pk %}">
                                                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{ customer.pk }}">
                                                          <i class="bi bi-trash-fill"></i>
                                                        </button>
                                                    </form>

                                                     <!-- Modal -->
                                                        <div class="modal fade" id="exampleModal{{ customer.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                          <div class="modal-dialog">
                                                            <div class="modal-content">
                                                              <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">Вы хотите удалить контрагента {{ customer.name }}?</h5>
                                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                              </div>
                                                              <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                                                                <form action="{% url "webapp:customer_del" customer.pk %}" method="post">
                                                                    {% csrf_token %}
                                                                    <button class="btn btn-primary btn-danger">Да</button>
                                                                </form>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                {% endif %}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Наименование</th>
                                            <th>Телефон</th>
                                            <th>Адрес</th>
                                            <th>ИИН/БИН</th>
                                            <th>№паспорта/р.с.</th>
                                            <th>Редактировать</th>
                                            <th>Удалить</th>
                                        </tr>
                                    </tfoot>
                                </table>
                                {% if is_paginated %}
                                    {% include "partial/pagination.html" %}
                                {% endif %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>


{% endif %}
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <!-- jQuery -->
    <script src="{% static "assets/plugins/jquery/jquery.min.js"  %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static "assets/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <!-- DataTables -->
    <script src="{% static "assets/plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js" %}"></script>
    <script src="{% static "assets/plugins/datatables-responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js" %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static "assets/js/adminlte.min.js" %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static "assets/js/demo.js" %}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": false,
                "autoWidth": false,
            });
            $('#example2').DataTable({
                "paging": false,
                "lengthChange": false,
                "searching": false,
                "ordering": false,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

{% endblock javascripts %}